spring:
  application:
    name: helloService

#server:
#  port: 5000

#spring.datasource.username: root
#spring.datasource.password: root
#
#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost      
